#Application Config
spring:
  application:
    name: configuration-server
  #   profiles:
  #     active:
  #       - local,development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohitgith/configuration-server
          default-label: master
# Server Port
server:
  port: 8888
